### ISSUE TITLE
Being able to collapse the navigation part

### ISSUE THREAD

**Issue by JurajKubelka** [pharo-ide/Calypso#165]
Sometimes I keep Calypso open in one method to learn from it. I would appreciate if it is possible to have an action (button at the center-right Calypso window part?) to collapse the navigation part and see only the source code (tabs) below. That way, the window could occupy a less desktop space.

What do you think? Is it feasible? If so, I could try it as an extension (command) by myself, but I need some help on how to do it.

Also the collapsing strategy could depend on a method length. If the method is short (everything is visible), the navigation part could collapse down (so the Calypso window could occupy only half of the original part). If the the method is long (not everything is visible), the navigation part could collapse up and the editing are could occupy the whole Calypso window.

**Comment by dionisiydk** [comment]
Others IDE's expand panels on double click. Maybe it would be good for what you want?

**Comment by JurajKubelka** [comment]
It might work. I think it is still good to see all the tabs (to be able to switch between them).
Having a visible button might be a bit more apparent that such feature exists.

**Comment by JurajKubelka** [comment]
Or maybe the splitter, that is currently invisible to user, could have a button (buttons). Something like this: 

![cod4x](https://user-images.githubusercontent.com/465505/35475644-be6e31b6-0380-11e8-9ad2-218b96e3ce22.png)
