### ISSUE TITLE
Removing methods using multiple selection breaks the browser

### ISSUE THREAD

**Issue by guillep** [pharo-ide/Calypso#236]
- Latest Pharo
- I multiple select several methods
- Cmd+X
- I'm prompted with the "see senders"
- methods are remove

- BUM `#selected` was sent to nil
And I have an exception whatever I click on from that moment on.

The only solution is to close it and reopen it...

**Comment by dionisiydk** [comment]
Also can't reproduce. Do you have more concrete scenario. What exact methods and in what class?
