### ISSUE TITLE
Subscript out of bounds, right-clicking class pane

### ISSUE THREAD

**Issue by bencoman** [pharo-ide/Calypso#252]
1. Open fresh build 70793.
2. Open Calypso
3. Select AST-Core-Traits
4. Right-click on background of class window.
==>SubscriptOutOfBounds: 1

Array(Object)>>errorSubscriptBounds:
Array(Object)>>at:
Array(SequenceableCollection)>>first
ClyClassContextOfFullBrowser(ClyBrowserContext)>>lastSelectedItem
ClyBrowseCoveringTestCaseCommand class>>canBeExecutedInContext:
ClyClassContextOfFullBrowser(CmdToolContext)>>allowsExecutionOf:
CmdContextMenuCommandActivation(CmdCommandActivationStrategy)>>isActiveInContext:
CmdCommandActivator>>canExecuteCommand
CmdCommandActivator>>buildContextMenu:
CmdCommandMenuItem>>buildContextMenu:
[ :each | each buildContextMenu: aMenu ] in ClyQueryMenuGroup(CmdMenuGroup)>>inlineContextMenuItemsInto: in Block: [ :each | each buildContextMenu: aMenu ]
SortedCollection(OrderedCollection)>>do:
ClyQueryMenuGroup(CmdMenuGroup)>>inlineContextMenuItemsInto:
ClyQueryMenuGroup(CmdMenuGroup)>>buildContextMenu:
[ :each | each buildContextMenu: aMenu ] in CmdRootMenuGroup(CmdMenuGroup)>>inlineContextMenuItemsInto: in Block: [ :each | each buildContextMenu: aMenu ]
SortedCollection(OrderedCollection)>>do:
CmdRootMenuGroup(CmdMenuGroup)>>inlineContextMenuItemsInto:
CmdRootMenuGroup(CmdMenuGroup)>>buildContextMenu:
CmdMenu>>buildContextMenuFor:
CmdContextMenuCommandActivation class(CmdMenuCommandActivationStrategy class)>>buildContextMenuFor:inContext:
ClyQueryView>>menuColumn:row:
ClyCollapsedDataSource(ClyDataSource)>>menuColumn:row:
FTTableMorph>>showMenuForRowIndex:columnIndex:
FTTableMorph>>showMenuForPosition:
FTTableMorph>>click:

**Comment by dionisiydk** [comment]
In v0.11.3
