### ISSUE TITLE
Generate test option

### ISSUE THREAD

**Issue by jecisc** [pharo-ide/Calypso#257]
In Nautilus there was an option to generate a test and jump to it.

Is it somewhere in Calypso? If not, is it planned?

![pharo_2018-04-25_00-13-52](https://user-images.githubusercontent.com/9519971/39216897-e1bfa9b0-481d-11e8-9683-f969bc920850.png)

**Comment by dionisiydk** [comment]
These functions was very badly implemented. All in NautilusUI. So I simply ignore them. Especially that I did not use them.

So the plan is add items when people will really ask them. Issues are such requests :)

**Comment by zecke** [comment]
+1 for the feature. I almost always use that feature.

**Comment by dionisiydk** [comment]
Ok. It will be done.
I am not missed it because of first test approach.

**Comment by dionisiydk** [comment]
in v0.14.1
