### ISSUE TITLE
Icons hitbox area are too small

### ISSUE THREAD

**Issue by jecisc** [pharo-ide/Calypso#260]
Just look at this screen:

![image](https://user-images.githubusercontent.com/9519971/39405718-08b7015a-4baa-11e8-80cc-3aa3bc2dfe40.png)

It's crazy small. When I try to click on it I lose a lot of time to get it right because it's so small.

**Comment by dionisiydk** [comment]
Is it different in Nautilus? I am sure that I used same icons

вс, 29 апр. 2018 г., 12:38 CyrilFerlicot <notifications@github.com>:

**Comment by jecisc** [comment]
![image](https://user-images.githubusercontent.com/9519971/39411666-e49358a4-4c0e-11e8-92cb-44535f3217e6.png)


Here is the hitbox in Nautilus. 

There is at least 5 more pixels on each side.

**Comment by dionisiydk** [comment]
Ok. Icon is same. Problem with surrounding space
