### ISSUE TITLE
Not enough source code options if we select the end of the method

### ISSUE THREAD

**Issue by jecisc** [pharo-ide/Calypso#261]
When I finish writing a method I like to format it. But because of a Pharo bug, I need to use the context menu on windows. 

If I right click in the middle of the method I get the "source code" submenu in the contextual menu and the format option inside.

If I right click after the last character, the cursor appears after the last character and I don't have the source code options in the contextual menu, thus I cannot format. 

Since I work with a lot of small functions in a big screen I always right click after the last character and this is really annoying :(

Maybe this is not a calypso bug but an ast one but since I'm not sure I open the issue here.

**Comment by dionisiydk** [comment]
For the record: same problem exists for suggestions in Nautilus

**Comment by dionisiydk** [comment]
Seems the problem with #bestNodeFor: . It returns nil for interval which is out of last statement.
When last statement is a return node it does not work for any following cursor position.

**Comment by dionisiydk** [comment]
The right solution would be fixing this method RBProgramNode>>#bestNodeFor: to return methodNode instead of nil.
But I will add similar fix to calypso logic to cover Pharo 6.

**Comment by jecisc** [comment]
Weird for Nautilus.

This is a screen in P6.1 when I right click after the last line:

![image](https://user-images.githubusercontent.com/9519971/39418915-6ed136d2-4c5d-11e8-8130-19e911d24d3d.png)

**Comment by dionisiydk** [comment]
In v0.11.3
