### ISSUE TITLE
Spelling in Critics "Uses or's instead of a searching literal"

### ISSUE THREAD

**Issue by riverdusty** [pharo-ide/Calypso#265]
Checks for repeated literal **_equalitity_** tests that should rather be implemented as a search in a literal collection.

tity made me giggle...

**_equalitity_** should be **_equality_**

**Comment by riverdusty** [comment]
Its in the critics browser, screen shot attached.
![calypsospellingerror](https://user-images.githubusercontent.com/572263/39802438-551ba638-536e-11e8-89ec-530a4be0a68f.png)

**Comment by dionisiydk** [comment]
Ah, it is not Calypso. It is part of critiques package. Please, open Pharo issue for this.
