### ISSUE TITLE
Renaming instance variables

### ISSUE THREAD

**Issue by bliznjan** [pharo-ide/Calypso#305]
I cannot find a way to rename an instance (or class) variable as refactoring that rewrites its name in all occurences for me. In Nautilus this functionality used to be in Refactoring context menu item of a class.

**Comment by dionisiydk** [comment]
Two ways:
- Switch to var mode (instead of protocol). Select var and run command from
menu or cmd+r.
- Select var in method source code and run command from Source code submenu
or cmd+r

ср, 1 авг. 2018 г., 9:37 Jan Blizničenko <notifications@github.com>:

**Comment by bliznjan** [comment]
Nice, both ways work, thank you.
