### ISSUE TITLE
classify method does not works when coming from cmd+/

### ISSUE THREAD

**Issue by estebanlm** [pharo-ide/Calypso#324]
Trying to classify a method is not working, I don't know if always or just in some conditions.

**Comment by dionisiydk** [comment]
There are two commands:
- classify methods from method pane
- classify method from method editor
First one modifies protocol of selected methods.
Last one modifies protocol of method in editor. But change is applied only if editor is not dirty. If editor is dirty it only changes the editor state (indicated in status bar). In that case "accept changes" will apply new protocol (together with method changes).

So my guess is that you execute second command in dirty editor. Question how to improve this logic? (if is really bad)

**Comment by estebanlm** [comment]
yes. Thats what seems to be happening. 
but it needs to be improved because is super confusing.
Those are two different operations, hence both are called "classify method" = **BAD!**. 
I guess one can be called "move to protocol" and the other "classify currently edited method". Then it can be more or less disambiguated.
Now, I understand you do not want "move to protocol" because it should be a tag of many. But this is not really clear and tomorrow what is a single choice could be a multiple choice, keeping the name. 
But of course, since both commands are the same, is hard to define a name.

**Comment by estebanlm** [comment]
if I add 
```
ClyRequestMethodTagForEditorCommand>>canBeExecutedInContext: aToolContext
	^ aToolContext tool isKindOf: ClyMethodCodeEditorToolMorph 
```
it will do "kind of" what I'm looking for, at the price of losing the one that should change protocol on "in editor" method (which never worked with cmd+/ btw)

**Comment by dionisiydk** [comment]
Ah, you are right. Command was available in any text editor which is wrong.
But you need to use superclass ClyMethodEditorToolMorph (command is valid for method creation too)

**Comment by dionisiydk** [comment]
And renaming command is not needed in that case because it was not the rood of problem I guess.
(we already have many "rename" items with cmd+/. And it not looks bad because there are groups for each of them).

**Comment by estebanlm** [comment]
ok, not renaming. 
if there are no further objections, I will integrate this :)

**Comment by dionisiydk** [comment]
Hi Esteban.
Look at PR. I ask you questions

**Comment by dionisiydk** [comment]
I comment PR again. Not sure if you receive notifications.

**Comment by estebanlm** [comment]
yeah, I saw it. Just no time to work on it until now.
