### ISSUE TITLE
do not show trait method if method is override in class

### ISSUE THREAD

**Issue by estebanlm** [pharo-ide/Calypso#328]
now, when you override a trait method in a class, you still see the trait.
this is wrong: since using a trait is about composition, once override the method is not anymore part of the class.
- is confusing to users
- is "technically" incorrect

**Comment by dionisiydk** [comment]
It duplicates #304

**Comment by dionisiydk** [comment]
But look wider. It is not technically incorrect. It is about technical details of trait implementation. You can look at objects from very various angles which represented by scopes. Each cover particular use case and use preference.

Problem that now there is no behaviour to hide overridden methods in inherited scope. And it needs to be implemented.
