### ISSUE TITLE
cmd+/ does not works on windows

### ISSUE THREAD

**Issue by estebanlm** [pharo-ide/Calypso#329]
and probably also does not works on azerty

(while probably this is not a calypso problem but something related to keybindings I let it here because here is where it shows up and I can dig into it)

**Comment by dionisiydk** [comment]
Maybe you will also have time for 21967
<https://pharo.fogbugz.com/f/cases/21967/Character-enter-asShortcut-does-not-work-as-key-combination-subscription-of-morph>
.

2018-09-20 10:09 GMT+01:00 Esteban Lorenzano <notifications@github.com>:

**Comment by estebanlm** [comment]
Mmm. This seems to be a more general mapping problem too. For example `ctrl+shift+S` does not works either.

**Comment by estebanlm** [comment]
meh :/ 
easiest way is to map it into cmd+h instead (that will not have problems for other users).

**Comment by estebanlm** [comment]
at the end, I will change the activation key to cmd+h 
this will work on windows, linux and mac without problem. 
and I will also add an icon in the text toolbar... even if is not the "right place", it will contribute to make it visible.
