### ISSUE TITLE
Scopes do not work in method browsers opened with `ClyQueryBrowser browseMethods:`

### ISSUE THREAD

**Issue by dupriezt** [pharo-ide/Calypso#331]
For example, run:
`ClyQueryBrowser browseMethods: (SystemNavigation default allMethodsSelect: [ :aMethod | aMethod containsHalt])`
This opens a method browser showing all the methods that contain 'halt'. In this method browsers; the scopes do not work. For example choosing the "Packages: Kernel-Tests" scope does not remove the methods from other packages.

**Comment by dionisiydk** [comment]
Yes. In that case special ClyConstantMethodQuery is used and it does not use scope at all.
It can be fixed.
But for your case (halts) it is better to implement real queries. There is already ClyActiveBreakpoints query:
```Smalltalk
ClyQueryBrowser openOn: ClyActiveBreakpoints new
```
It gives auto updating browser
