### ISSUE TITLE
Debug test do not work after pressing ⌘D

### ISSUE THREAD

**Issue by fortizpenaloza** [pharo-ide/Calypso#364]
It works after pressing ⌘+Shift+D. If it is the expected behavior it must be reflected in the contextual pop-up.

**Comment by fortizpenaloza** [comment]
I have the fix but no have permission to create a new branch from `dev` (I assumed that's the one I should branch and then create a PR against).

**Comment by jecisc** [comment]
Hi,

For this case, you should fork Calypso, commit the fix in a branch of your fork, and then create a pull request to this repository.

I don't have the time to give more details :(

**Comment by fortizpenaloza** [comment]
Ok, I'll do that. Thanks

**Comment by fortizpenaloza** [comment]
Done. It would help a lot to have a "how to contribute" guide.

Keep up the good work!

**Comment by fortizpenaloza** [comment]
#365 fixed this one

**Comment by dionisiydk** [comment]
in v0.14.1
