### ISSUE TITLE
Inline temp is unavailable when full assignment is selected

### ISSUE THREAD

**Issue by fortizpenaloza** [pharo-ide/Calypso#366]
While editing code on 6.1 after pressing ⌘T a contextual pop-up opened with suggestions according to the selected code.

In the following example, I'm selecting an assignation to a temp and it suggests me to perform an `inline temporary`.
![screen shot 2018-11-21 at 11 26 20](https://user-images.githubusercontent.com/90245/48847474-66bc1880-ed80-11e8-87a4-f1da0102851b.png)

Now with Calypso, it gives me irrelevant options for the selected code. See:
![screen shot 2018-11-21 at 11 29 28](https://user-images.githubusercontent.com/90245/48847682-e77b1480-ed80-11e8-94fa-35cc7c2ef6c9.png)

*Am I the only one who found it useful?*

**Comment by dionisiydk** [comment]
In Calypso "Inline temp" command is available for selected temp variable. Not for selected assignment.
I found always frustrating that in Nautilus it was required to manually find assignment of variable to inline it. And I think Calypso way is more logical from the point of view of command name: to inline variable you need to select/choose what variable to inline. So I am not sure that we need a feature to have this command when assignment is selected.

If you think that command is in fact an assignment inline then it never supported multiple assignment in method and therefore it does not make sense.

Also notice that old style suggestions menu is replaced (and deprecated) in Calypso with source code menu based on Commander.

**Comment by fortizpenaloza** [comment]
@dionisiydk thanks for clarifying how works now. It makes sense. I realize I never thought about how to improve it I just found it very useful.

Now, the new menu provides options like *extract method* when I select the assignment operator or the local variable 
![screen shot 2018-11-21 at 11 29 28](https://user-images.githubusercontent.com/90245/48847682-e77b1480-ed80-11e8-94fa-35cc7c2ef6c9.png)

And clicking that option gives me a debugger: 
![screen shot 2018-11-22 at 08 00 36](https://user-images.githubusercontent.com/90245/48899403-48145b00-ee2e-11e8-898f-4e258b6eacd7.png)

Do I create an issue for this?

**Comment by dionisiydk** [comment]
It is general issue with refactoring errors. Look also into #370 .

**Comment by dionisiydk** [comment]
in v0.14.1
