### ISSUE TITLE
Issue with a system announcement after running tests

### ISSUE THREAD

**Issue by fortizpenaloza** [pharo-ide/Calypso#385]
Hi,

I've got a debugger after running [Chalten](https://github.com/ba-st/chalten) tests on Pharo 7. 

Chalten defines a lot of globals. It defines one called `TimeUnits` initialized to an instance of `TimeUnitsGlobals`. And has a `TimeUnitsTest` to test it. 

So after running them, the heuristics on `ClyTestedEnvironmentPlugin#findTestedClassCoveredBy:ifAbsent:` tries to get a class and, upper on the stack, on `ClassAnnouncement#packageAffected` it sends #package to this instance opening the debugger.

I can try to provide a PR improving `ClySystemEnvironment#classNamed:ifAbsent:` since it performs a look-up on globals but not all globals are classes (i.e. Processor). Do you agree?

**Comment by dionisiydk** [comment]
You are right. I did PR. 
Thanks for report.

**Comment by dionisiydk** [comment]
in v0.14.1
