### ISSUE TITLE
Calypso-SystemQueries is dirty package in P7

### ISSUE THREAD

**Issue by astares** [pharo-ide/Calypso#386]
In Pharo 7.0.0
Build information: Pharo-7.0.0+rc1.build.44.sha.d3be1c018447fa5f7ba666cea7aff396f36d4309 (64 Bit)

when you run 

  RPackageOrganizer default packages select: [:each | each isDirty ]

the package "Calypso-SystemQueries" is a dirty package.

are left anymore.

Pharo issue on that topic is: https://pharo.fogbugz.com/f/cases/22776/

**Comment by pavel-krivanek** [comment]
I see no problem in the Calypso code or packages. This package starts to be dirty during the loading of this method: 
`ClyClass9FromPExtendedByP5>>#extensionMethod2FromClass9` 
...that is placed in `Calypso-SystemQueries-Tests-P5WithTags`

I guess it is a Monticello issue. It is probably not able to correctly determine the package that should be dirty.

**Comment by pavel-krivanek** [comment]
https://pharo.fogbugz.com/f/cases/22871/MC-makes-dirty-more-packages-than-expected

**Comment by estebanlm** [comment]
integrated
