### ISSUE TITLE
Debugger code highligt broken when using debugTest menu

### ISSUE THREAD

**Issue by demarey** [pharo-ide/Calypso#400]
See full explanation here: https://pharo.fogbugz.com/f/cases/22823/Debugger-code-highligt-broken-when-using-debugTest-menu

The solution is to not use a one-shot breakpoint. It is not a problem since Calypso ensure that the breakpoint is removed after running the tests.

**Comment by demarey** [comment]
issue for SystemCommands project

**Comment by dionisiydk** [comment]
in v0.14.1
