### ISSUE TITLE
Unecessary dialogs during rename

### ISSUE THREAD

**Issue by jecisc** [pharo-ide/Calypso#421]
I wanted to rename a method and during one rename I got two times a window "This will modify all 3 implementors. Ok/Cancel".

First, the fact that I got the window 2 times is wrong.

Second, since we are asked to select the methods to delete/add I think it is useless to display this warning.

**Comment by dionisiydk** [comment]
https://pharo.manuscript.com/f/cases/22894/Unecessary-dialogs-during-refactorings

**Comment by dionisiydk** [comment]
fixed in v0.15.1

**Comment by dionisiydk** [comment]
> Second, since we are asked to select the methods to delete/add I think it is useless to display this warning.

Please open issue for Pharo for this case because it is behaviour of RB refactoring.
