### ISSUE TITLE
Cannot remove a class that has spurious references to it

### ISSUE THREAD

**Issue by dupriezt** [pharo-ide/Calypso#424]
Steps:
- Fresh pharo image with calypso dev branch loaded (commit a300298)
- Create a class "MyClass"
- Try to remove it (ctrl-X or right-click/"remove")
- A dialog saying "There are 2 references to MyClass. Show them?" appears.

The problem is that while there are references to MyClass, They are not actually related to the class I just created. Since there is no option to "remove anyway" MyClass, I can't remove MyClass without modifying the foreign code with these 2 spurious references to MyClass.

**Comment by dionisiydk** [comment]
It is behaviour of RBRemoveClassRefactoring which do this logic.
I checked that Nautilus does not use it which explains why it was correct there.

SycRemoveClassCommand should handle this case

**Comment by dionisiydk** [comment]
I am wrong with my explanation. The users check is sone on calypso level in this case

**Comment by dionisiydk** [comment]
https://pharo.manuscript.com/f/cases/22895/Cannot-remove-a-class-that-has-spurious-references-to-it

**Comment by dionisiydk** [comment]
And it requires new SystemCommands https://github.com/pharo-ide/SystemCommands/pull/64
