### ISSUE TITLE
Error when creating a setUp method for a test

### ISSUE THREAD

**Issue by dupriezt** [pharo-ide/Calypso#425]
Steps:
- Fresh pharo image with calypso loaded on dev branch (commit a300298)
- Create a class MyTestClass, subclass of TestCase
- Click on the "setUp" tab of calypso and edit the setUp method
- When saving the edits to #setUp, an error is raised:
![image](https://user-images.githubusercontent.com/32486709/51105869-81dc5f00-17ea-11e9-9c2e-97f45476588f.png)

Clicking on the "Inst. side method" tab and "creating" a method named setUp works. And after that, the setUp method can be edited directly from the setUp tab without problems.

**Comment by dionisiydk** [comment]
Fixed in 0.15.2
