### ISSUE TITLE
Class initialize button problem when installed from a Trait 

### ISSUE THREAD

**Issue by vitormcruz** [pharo-ide/Calypso#444]
When a class SomeClass uses a trait that implements:

```
SomeTrait class >> initialize

    self someMessage.
```

The button "Run Script" from Calypso executes initialize from SomeTrait class instead of SomeClass installed one. From Playgroung, executing:

    SomeClass someMessage

Works as expected.

**Comment by dionisiydk** [comment]
In 0.6.0
