### ISSUE TITLE
Calypso doesn't always correctly show the diamond indicator for an overridden method

### ISSUE THREAD

**Issue by macta** [pharo-ide/Calypso#445]
When creating some Exercism exercises  (see: /exercism/pharo-smalltalk.git) one of my exercises LeapTest doesn't show the triangle for methods that are overriden, however other similar examples in HelloWorldTest and AncronymTest do. I can't see what the difference is - the methods are identical.
(See photo's)

![image](https://user-images.githubusercontent.com/5553623/53326213-e7893400-38dc-11e9-88cb-cde86a4a2d81.png)

![image](https://user-images.githubusercontent.com/5553623/53326228-f1ab3280-38dc-11e9-8359-ba7f698f638b.png)

**Comment by dionisiydk** [comment]
Good catch Tim.
It does not handle class side overrides when class definition changed (which affects those class side overrides)
