### ISSUE TITLE
Move methods to class doesn't appear in menu (but there is a command)

### ISSUE THREAD

**Issue by macta** [pharo-ide/Calypso#448]
I wanted to move methods to another class and it wasn't showing - starting writing my own command then then discovered there is already one present - SycMoveMethodsToClassCommand

however . think it is missing the annotation to make it appear - looking at other commands they have:
```
methodMenuActivation
	<classAnnotation>
	
	^CmdContextMenuActivation byRootGroupItemFor: ClyMethod asCalypsoItemContext 
```
Adding this makes it then appear - is this the correct fix?

**Comment by dionisiydk** [comment]
Yes.

Also notice that all commands in Calypso are managed in same way. If you
already see that something is executed by drag and drop (for example) then
it can be added to menu and as a shortcut. And if there is menu item then
you can add shortcuts and even drag and drop if it make sense.

Besides all these command annotations can be packaged in your own calypso
extension. So it's not necessary to convince particular configuration to be
default in Pharo. And all this logic should be applicable to Iceberg
commands too (including toolbar items).


ср, 27 февр. 2019 г. в 21:14, Tim Mackinnon <notifications@github.com>:

**Comment by macta** [comment]
You need to be an admin to move this - I think you are right @dionisiydk ?

**Comment by dionisiydk** [comment]
Add PR. I am ok with it

**Comment by dionisiydk** [comment]
In 0.6.0
