### ISSUE TITLE
New method tab disappear

### ISSUE THREAD

**Issue by Alisu** [pharo-ide/Calypso#453]
It happends to me a few times and i have no idea how to reproduce.

The new method tab which show 

```
messageSelectorAndArgumentNames
	"comment stating purpose of message"

	| temporary variable names |
	statements
```

doesn't appear anymore after some time. My only option is to open a new calypsoBrowser.

**Comment by astares** [comment]
- which image version exactly? (see Help -> About box)
- is this in a modified image?

Any steps to be able to reproduce this ...

**Comment by Alisu** [comment]
Pharo 7 64bits, no mdification on the image.

**Comment by dionisiydk** [comment]
Confirm. It disappears in variables mode

пн, 11 мар. 2019 г. в 11:57, Alisu <notifications@github.com>:
